build:
	# build image
	sudo docker build -t="zuev/neurolab" .

create:
	# create and start container
	sudo docker run -it --name neurolab -v /home/user/dev/neurolab:/neurolab zuev/neurolab cd neurolab
start:
    # Start container
	sudo docker start -i neurolab

